- hosts: hdfsnamenode
  vars_prompt:
    - name: folder
      prompt: Provide a folder name for hdfs.
      private: no
      
  tasks:
      #  - name: copy some files
      #    copy: 
      #        src: "{{ item  }}" 
      #        dest: /root
      #    loop: 
      #        - hadoop-1.2.1-1.x86_64.rpm
      #        - jdk-8u171-linux-x64.rpm
      # 
  - name: Install hadoop and jdk package.
    command:  "rpm -ivh  /home/ec2-user/hadoop-1.2.1-1.x86_64.rpm  /home/ec2-user/jdk-8u171-linux-x64.rpm --force"
  - name: Creating a folder using root storage.
    file:
          path: "{{ folder }}"
          state: directory

  - name: Copy config files.
    template: 
        src: hdfs-site.xml
        dest: /etc/hadoop/hdfs-site.xml

  - name: Copy config files.
    template:
        src: core-site.xml
        dest: /etc/hadoop/core-site.xml

  - name: Formatting namenode
    shell: "echo Y | hadoop namenode -format "  

  - name: Starting Datanode Service
    command: "hadoop-daemon.sh start namenode"
  - name: edit rc.local file to make the service permenant.
    lineinfile:
        path: /etc/rc.d/rc.local
        line: 'hadoop-daemon.sh start namenode'
  - name: Executing rc.local file
    command: "chmod +x /etc/rc.d/rc.local"

