- hosts: mapred_task_tracker
  vars_prompt:
    - name: jt_ip
      prompt: Mention ip of mapred_jobtracker
      private: no

  tasks:
  - name: Install hadoop and jdk package.
    command:  "rpm -ivh  /home/ec2-user/hadoop-1.2.1-1.x86_64.rpm  /home/ec2-user/jdk-8u171-linux-x64.rpm --force"

  - name: Copy config files.
    template: 
        src: tt-mapred-site.xml
        dest: /etc/hadoop/mapred-site.xml
  - name: Starting Datanode Service
    command: "hadoop-daemon.sh start tasktracker"
  - name: edit rc.local file to make the service permenant.
    lineinfile:
        path: /etc/rc.d/rc.local
        line: 'hadoop-daemon.sh start tasktracker'
  - name: Executing rc.local file
    command: "chmod +x /etc/rc.d/rc.local"
           
